### PR TITLE
Update Japanese translation for v3.8

### PR DESCRIPTION
**Pull request by Cai0407**
update and fix Japanese translation of v3.8 release

### CODE REVIEW

**Review by RealRaven2000 — COMMENTED** [review]
I am merging most changes now - not sure I agree with translating "Pro" and "Standard" as these are part of a product, I would rather keep "SmartTempaltes Pro" where is makes sense

**Comment by RealRaven2000** [comment]
I just pushed the curated changes to the ESR91 branch.

**Comment by Cai0407** [comment]
Thank you for reviewing!
I have updated the translation.

1. in most cases, keeping "Pro" and "Standard" untranslated (translated to "プロ" and "標準" before)
2. fix small typos

**Review by RealRaven2000 — APPROVED** [review]
thanks for reviewing, looking good!

**Pull request merged**
